"""added section in student model

Revision ID: 60649728f254
Revises: e03a04c73283
Create Date: 2023-09-27 21:36:41.020687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60649728f254'
down_revision = 'e03a04c73283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
