"""empty message

Revision ID: bfae4b6e435f
Revises: 60649728f254
Create Date: 2023-09-27 23:53:59.524495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfae4b6e435f'
down_revision = '60649728f254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('email_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('email_address', ['student_email_address'], unique=False)

    # ### end Alembic commands ###
